"""Candidate Model

Revision ID: 3eff0f7cf2e9
Revises: 6891023f4b37
Create Date: 2023-09-11 20:28:27.731128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eff0f7cf2e9'
down_revision = '6891023f4b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('interview_video', sa.Text(), nullable=True),
    sa.Column('is_report_generated', sa.Boolean(), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
